Document report
LL04-Finance-Dowell/100018-dowellWorkflowAi-testing pull request #182
Opened 2023-11-24 12:50 UTC by Morvin-Ian

2023-11-27 06:46 UTC, coderboy-exe reviewed
Looks good but I'm not sure why there is a url in line 27 of thr requirements file. Care to explain or look into that? Is it necessary or can it be removed? @Morvin-Ian

2023-11-27 07:12 UTC, coderboy-exe requested changes
Please look at my previous comment:

https://github.com/LL04-Finance-Dowell/100018-dowellWorkflowAi-testing/pull/182#pullrequestreview-1749708990

2023-11-28 02:59 UTC, coderboy-exe commented
> > Yeah Its neccessary, The spacy model package can be either small, medium, or large. That 27th line downloads the smaller one which we are using.

All clear for merge @WawinyEdwin

2023-11-28 06:13 UTC, WawinyEdwin requested changes

2023-11-28 09:33 UTC, Morvin-Ian commented on app/urls_v2.py
> +    path("reports/document/<str:item_id>/", views_v2.DocumentReport.as_view(), name="document-report"),
Okay

2023-11-30 06:44 UTC, WawinyEdwin approved these changes

2023-11-30 06:45 UTC, merged