Backend 2
LL04-Finance-Dowell/100018-dowellWorkflowAi-testing pull request #52
Opened 2023-06-19 05:37 UTC by Couzy21

2023-06-19 16:06 UTC, WawinyEdwin commented on app/urls.py
The folder update endpoint should be a PUT request, to the endpoint `folders/<str:folder_id>` We don't need an extra endpoint for that

2023-06-19 16:12 UTC, WawinyEdwin commented on app/utils/mongo_db_connection.py
1. Stick to the existing convention of naming functions, No need to introduce new conventions like `update_folder_db`
2. The save_template() function is used in a number of views, by introduing another parameter that means all its occurence will break, make sure other occurences are updated as well or introduce defaults.
3.  document_in_folder() -  your function names should be self descriptive, by looking at this functions name I can tell what it does, again follow the existing convention.

2023-06-19 16:19 UTC, WawinyEdwin commented on app/views.py
1. Stick to convention, now in this file we have two methods that look like they do the same thing `folder_update()` and `update_folder()`. Have one view that does the single folder retrival and folder update don't mix up things.
2. Configure Black formatter on your VsCode. So that the code has a consistent styling, I should not be seeing formatting changes.
3. Self-Review your code before commit and remove comments that are not required and are unnecessary.
4. Make sure that all existing functionality of the products works and is not affected by your new changes

2023-06-19 18:01 UTC, Couzy21 commented on app/views.py
Done

2023-06-19 18:27 UTC, WawinyEdwin requested changes

2023-06-19 18:27 UTC, WawinyEdwin commented on app/urls.py
Do we have a endpoint to fetch the folder details?

2023-06-19 18:27 UTC, WawinyEdwin commented on app/utils/mongo_db_connection.py
I see changes to `save_document()` that relate to its parameter structure, Are you aware that this function is used across helpers and class function that implement processing functionality like cloning document,. Did you consider that how adding an extra parameter will affect all occurrences where the function is called.
- Refactor that and make sure nothing breaks
 
The `document_in_folder()` and `template_in_folder()` function names are not refactored for convention and descriptiveness, those two are too vague.

2023-06-19 18:27 UTC, WawinyEdwin commented on app/views.py
Do not be hasty in making those changes, Make sure you are doing things right and self review before requesting me to review again.
Lastly understand the codebase.

2023-06-20 18:13 UTC, WawinyEdwin approved these changes
I am merging this, make sure the integration on frontend side is completed by end of tommorow

2023-06-20 18:13 UTC, merged